
# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [4]:
# Write your code here
import pandas as pd
 
df = pd.DataFrame({
    'City' : ["Bhopal", "Indore", "Bhopal", "Delhi"]
})
#returns the count of unique values
print(df.nunique())

#for exact value we use 
print(df['City'].unique())

City    3
dtype: int64
<ArrowStringArray>
['Bhopal', 'Indore', 'Delhi']
Length: 3, dtype: str


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [ ]:
# Write your code here
#used to get the number of unique values in any col
df['City'].nunique()

3


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [ ]:
# Write your code here
df['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [8]:
# Write your code here
df = pd.DataFrame({
    'City' : ["Bhopal", "Bhopal", "Delhi"],
    'Marks' : [80, 90, 70]
})

df.groupby('City')['Marks'].mean()

City
Bhopal    85.0
Delhi     70.0
Name: Marks, dtype: float64


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [10]:
# Write your code here
df.sort_values(by='Marks')

     City  Marks
2   Delhi     70
0  Bhopal     80
1  Bhopal     90


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [11]:
# Write your code here
df.sort_values(by='Marks', ascending=False)

     City  Marks
1  Bhopal     90
0  Bhopal     80
2   Delhi     70


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [12]:
# Write your code here
print(df[df.Marks > 75])

     City  Marks
0  Bhopal     80
1  Bhopal     90


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [14]:
# Write your code here
df = pd.DataFrame({
    'City' : ["Bhopal", "Bhopal", "Delhi"],
    'Age' : [20,21,31],
    'Marks' : [80, 90, 70]
})

print(df[(df.Marks > 70) & (df.Age) > 20])

Empty DataFrame
Columns: [City, Age, Marks]
Index: []


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Department' : ['HR','HR','IT','IT','HR','IT'],
    'Salary' : [20000, 25000, 12000, 13000, 24000, 12500]
})
#group department on the basis of salary and sum them
df.groupby('Department')['Salary'].sum()

Department
HR    69000
IT    37500
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [20]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Shreyash','Ankit','Aryan'],
    'City' : ["Bhopal", "Indore", "Delhi"],
    'Age' : [20,21,31],
    'Marks' : [80, 90, 70]
})
print(df['City'].unique())
print(df.City.value_counts())
print(df[df['Marks'] > 80])
print(df.sort_values(by='Marks'))

<ArrowStringArray>
['Bhopal', 'Indore', 'Delhi']
Length: 3, dtype: str
City
Bhopal    1
Indore    1
Delhi     1
Name: count, dtype: int64
    Name    City  Age  Marks
1  Ankit  Indore   21     90
       Name    City  Age  Marks
2     Aryan   Delhi   31     70
0  Shreyash  Bhopal   20     80
1     Ankit  Indore   21     90