
# Pandas Final Assignment (Class 2 + Class 3)

### Topics Covered
- head()
- tail()
- info()
- shape
- dtypes
- loc
- iloc
- rename()
- set_index()
- reset_index()
- isnull()
- fillna()
- astype()
- replace()
- drop()
- duplicated()
- drop_duplicates()

### Instructions
- Use Pandas in every question.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display First Rows

## Problem Statement
Create the following DataFrame:

| Name | Age |
|------|-----|
| Aman | 21 |
| Rahul | 22 |
| Neha | 20 |
| Priya | 23 |
| Ravi | 24 |

Display the first 3 rows using `head()`.

## Sample Output
```python
First 3 rows of DataFrame
```

In [1]:
# Write your code here
import pandas as pd

df = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha', 'Priya', 'Ravi'],
    'Age' : [21, 22, 20, 23, 24]
})

df.head(3)

    Name  Age
0   Aman   21
1  Rahul   22
2   Neha   20


# Q2. Display Last Rows

## Problem Statement
Create a DataFrame containing 6 student records.

Display the last 2 rows using `tail()`.

## Sample Output
```python
Last 2 rows of DataFrame
```

In [2]:
# Write your code here
df.tail(2)

    Name  Age
3  Priya   23
4   Ravi   24


# Q3. Check DataFrame Information

## Problem Statement
Create a DataFrame containing:

```python
Name = ["Aman","Rahul","Neha"]
Marks = [80,75,90]
```

Display DataFrame information using `info()`.

## Sample Output
```python
<class 'pandas.core.frame.DataFrame'>
...
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Aman', 'Rahul', 'Neha'],
    'Marks' : [80 ,75, 90]
})
df.info() #returns every usefull infomation about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Marks   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 193.0 bytes


# Q4. Shape and Data Types

## Problem Statement
Create a DataFrame with:

```python
Name
Age
City
```

Print:
- Shape
- Data Types

## Sample Output
```python
(3,3)
object
int64
```

In [5]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Shreyash', 'Anishka', 'Anushka'],
    'Age' : [20, 20, 19],
    'City' : ['Bhopal', 'Bhopal', 'Indore']
})
print(df)
print(df.shape)
print(df.dtypes)

       Name  Age    City
0  Shreyash   20  Bhopal
1   Anishka   20  Bhopal
2   Anushka   19  Indore
(3, 3)
Name      str
Age     int64
City      str
dtype: object


# Q5. Select Data using loc

## Problem Statement
Create a DataFrame with Name, Age and City.

Using `loc`, display the Name and City of the first row.

## Sample Output
```python
Name    Aman
City    Bhopal
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Shreyash','Aman','Tanishq'],
    'Age' : [20, 21, 19],
    'City' : ['Bhopal', 'Indore', 'Kerela']
})
print(df.loc[0, 'Name']) #pass the parameters in form of list

Shreyash


# Q6. Select Data using iloc

## Problem Statement
Create a DataFrame with at least 4 rows.

Using `iloc`, print:
- Second row
- First two columns

## Sample Output
```python
Selected row values
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Shreyash' , 'Anushka' , 'Aman', 'Nidhi'],
    'Age' : [20, 22, 21, 20],
    'City' : ['Bhopal', 'Japan','Indore','Nepal'],
    'Height' : [101, 100, 98, 103]
})
#zero based indexing 
print(df)
print(df.iloc[1:2, 0:2])

       Name  Age    City  Height
0  Shreyash   20  Bhopal     101
1   Anushka   22   Japan     100
2      Aman   21  Indore      98
3     Nidhi   20   Nepal     103
      Name  Age
1  Anushka   22


# Q7. Rename a Column

## Problem Statement
Create a DataFrame:

```python
Name
Marks
```

Rename column `Marks` to `Score`.

## Sample Output
```python
Name  Score
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Shreyash' , 'Anushka' , 'Aman', 'Nidhi'],
    'Marks' : [80, 76, 79, 87]
})
df.rename(columns={'Marks': 'Score'}) #can use inplace to make the changes in the original df
print(df)

       Name  Marks
0  Shreyash     80
1   Anushka     76
2      Aman     79
3     Nidhi     87


# Q8. Handle Missing Values

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman", None, "Neha"]
Marks = [80, 75, None]
```

Fill missing values using `fillna()`.

## Sample Output
```python
Missing values replaced
```

In [ ]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Aman', None, 'Neha'],
    'Marks' : [80, 75, None]
})

#avoiding the use of inplace
df['Name'] = df["Name"].fillna('Unknown')
df['Marks'] = df['Marks'].fillna(0)
df

      Name  Marks
0     Aman   80.0
1  Unknown   75.0
2     Neha    0.0


# Q9. Replace Values

## Problem Statement
Create a DataFrame:

```python
City = ["BPL", "IND", "BPL"]
```

Replace:
- BPL → Bhopal
- IND → Indore

## Sample Output
```python
Bhopal
Indore
Bhopal
```

In [24]:
# Write your code here
df = pd.DataFrame({
    'City' : ["BPL", "IND", "BPL"]
})
df['City'] = df['City'].replace(['BPL', 'IND'], ['Bhopal', 'Indore'])
print(df)

     City
0  Bhopal
1  Indore
2  Bhopal


# Q10. Remove Duplicate Records

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman","Rahul","Aman","Neha"]
```

Check duplicate rows using `duplicated()` and remove them using `drop_duplicates()`.

## Sample Output
```python
Aman
Rahul
Neha
```

In [25]:
# Write your code here
df = pd.DataFrame({
    "Name" : ['Aman', 'Rahul', 'Aman' ,"Neha"]
})
print(df.duplicated())
df.drop_duplicates(inplace=True, keep='first')
print(df)

0    False
1    False
2     True
3    False
dtype: bool
    Name
0   Aman
1  Rahul
3   Neha